apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  containers:
  - name: test1
    image: docker.io/library/cirros:latest
    command: ["/bin/sh", "-c", "env"] 
    envFrom:
      - configMapRef:
          name: variables
