apiVersion: v1
kind: Pod
metadata: 
  name: pvc-test-pod
spec:
  containers:
  - name: centos
    image: centos:7
    command:
      - sleep
      - "3600" 
    volumeMounts:
      - mountPath: /nexus-data
        name: nexus
  - name: centos2
    image: centos:7
    command:
      - sleep
      - "3600"
    volumeMounts:
      - mountPath: /nexus-data-2
        name: nexus
  volumes: 
    - name: nexus
      persistentVolumeClaim:
        claimName: nexus
